# Generated by Django 3.0.3 on 2020-03-06 17:15

from django.conf import settings
from django.db import migrations, models
import forum.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0006_remove_post_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(forum.models.get_dummy_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='thread',
            name='user',
            field=models.ForeignKey(default=1, on_delete=models.SET(forum.models.get_dummy_user), to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
