# Generated by Django 3.0.3 on 2020-03-26 19:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20200326_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='thread',
            name='subject',
            field=models.TextField(max_length=2000, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
