# Generated by Django 3.0.3 on 2020-03-23 16:07

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200323_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='users/blank-profile-picture.svg', upload_to='users/'),
        ),
    ]
